modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="civitas_industria"
version="${mod_version}"
displayName="Civitas Industria"
description='''Industrial civilization, physical freight, commissioned factories and persistent regional ecology.'''
[[dependencies.civitas_industria]]
modId="neoforge"
type="required"
versionRange="[${neo_version}]"
ordering="NONE"
side="BOTH"
[[dependencies.civitas_industria]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="civitas_industria.mixins.json"

[[dependencies.civitas_industria]]
modId="adpother"
type="optional"
versionRange="[9.1.10.0]"
ordering="AFTER"
side="BOTH"

[[dependencies.civitas_industria]]
modId="create"
type="optional"
versionRange="[6.0.10]"
ordering="AFTER"
side="BOTH"

[[dependencies.civitas_industria]]
modId="immersiveengineering"
type="optional"
versionRange="[12.4.2-194]"
ordering="AFTER"
side="BOTH"

[[dependencies.civitas_industria]]
modId="adchimneys"
type="optional"
versionRange="[11.1.10.0]"
ordering="AFTER"
side="BOTH"
