modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="civitas_industria"
version="${mod_version}"
displayName="Civitas Industria"
description='''Industrial civilization foundation. Phase 0; no gameplay yet.'''
[[dependencies.civitas_industria]]
modId="neoforge"
type="required"
versionRange="[${neo_version}]"
ordering="NONE"
side="BOTH"
[[dependencies.civitas_industria]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
