package com.civitasindustria.test;
import com.civitasindustria.domain.*;
import java.util.*;
public final class RedesignChecks {
    private int checks;
    private void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
    private void rejects(byte[] data){boolean refused=false;try{CrownLedger.decode(data);}catch(IllegalArgumentException e){refused=true;}check(refused,"Damaged ledger accepted");}
    public static int run(){var t=new RedesignChecks();t.verify();return t.checks;}
    public static void main(String[] args){System.out.println("PASS: "+run()+" redesign checks");}
    private void verify(){var l=new CrownLedger();UUID a=new UUID(1,1),b=new UUID(2,2);check(!l.redeem(a)&&!l.buy(a,0)&&!l.sell(a,0),"Empty market creates value");check(l.deposit(a)&&l.balance(a)==100&&l.reserve()==1&&l.issued()==100,"Diamond backing");check(!l.transfer(a,b,-1)&&!l.transfer(a,a,1)&&!l.transfer(a,b,101),"Invalid payment");check(l.transfer(a,b,100)&&l.balance(a)==0&&l.balance(b)==100&&l.issued()==100,"Payment conservation");check(l.redeem(b)&&l.issued()==0&&l.reserve()==0,"Redemption burns");l.deposit(a);check(l.fund(a)&&l.treasury()==100&&l.balance(a)==0,"Market funding transfer");check(l.sell(a,0)&&l.stock(0)==1,"Market paid stocking");l.deposit(a);long before=l.balance(a);check(l.buy(a,0)&&l.sell(a,0)&&l.balance(a)<before,"Round trip profit");byte[] encoded=l.encode();check(Arrays.equals(encoded,CrownLedger.decode(encoded).encode()),"Canonical roundtrip");for(int i=0;i<encoded.length;i++)rejects(Arrays.copyOf(encoded,i));byte[] future=encoded.clone();future[3]=2;rejects(future);byte[] tail=Arrays.copyOf(encoded,encoded.length+1);rejects(tail);byte[] backing=encoded.clone();backing[11]++;rejects(backing);Random random=new Random(42);for(int i=0;i<10000;i++){UUID id=random.nextBoolean()?a:b;switch(random.nextInt(6)){case 0->l.deposit(id);case 1->l.redeem(id);case 2->l.transfer(id,id.equals(a)?b:a,random.nextInt(200));case 3->l.fund(id);case 4->l.buy(id,random.nextInt(4));case 5->l.sell(id,random.nextInt(4));}check(l.issued()==l.reserve()*100&&l.balance(a)+l.balance(b)+l.treasury()==l.issued(),"Random trade conservation");if(i%200==0)l=CrownLedger.decode(l.encode());}long supply=l.issued();for(int day=0;day<10000;day++){int prior=l.index();l.day(day,123);check(Math.abs(l.index()-prior)<=Math.max(1,prior*.02)&&l.index()>=5000&&l.index()<=20000,"Inflation bound");for(int good=0;good<4;good++)check(l.bid(good)<l.ask(good),"Price spread");}check(l.issued()==supply,"Demand minted money");check(!l.day(9999,123),"Same day replay");var raid=new RaidProgress();check(!raid.won(0)&&raid.ready(0,0),"Raid initial state");raid.spawned(0,0);check(!raid.won(0)&&raid.wave()==0&&!raid.ready(20,0),"Failed spawn counted as victory");for(int wave=1;wave<=3;wave++){check(raid.ready(wave*200,0),"Next wave not ready");raid.spawned(wave*200,6);check(raid.wave()==wave&&!raid.ready(wave*200+10,6)&&!raid.won(6),"Live wave prematurely advanced");}check(raid.won(0),"Third wave victory");raid.fail();check(!raid.won(0),"Retreat counted as victory");}
}
